- name: find unused messages
  hosts: localhost
  connection: local

  vars_files:
    - mozdev/vars/main.yml

  tasks:
    - name: check "jq" command
      shell:
        cmd: command -v jq

    - name: find unused messages
      script: >
        '{{ playbook_dir }}/mozdev/files/find_unused_messages.sh'
        '{{ src_path }}'
        '{{ ( find_unused_messages_ignores | join(';') ) if find_unused_messages_ignores is defined else '' }}'
