- name: find unused messages
  hosts: localhost
  connection: local
  vars_files:
    - mozdev/vars/main.yml
  tasks:
    - block:
        - name: check "jq" command
          shell:
            cmd: command -v jq
        - name: find unused messages
          script: "mozdev/files/find_unused_messages.sh '{{ src_path }}' '{{ find_unused_messages_ignores | join(';') }}'"
      when: find_unused_messages_ignores is defined
