- name: find unused messages
  hosts: localhost
  connection: local
  vars_files:
    - mozdev/vars/main.yml
  tasks:
  - name: check "jq" command
    command: command -v jq
  - name: find unused messages
    script: "mozdev/files/find_unused_messages.sh '{{ src_path }}'"

