- name: find unused messages
  hosts: localhost
  connection: local
  vars_files:
    - mozdev/vars/main.yml
  tasks:
  - name: check for jq-package
    become: true
    package:
      name: jq
      state: present
  - name: find unused messages
    script: "mozdev/files/find_unused_messages.sh '{{ src_path }}'"

