- name: install
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - mozdev

  tasks:
    - name: install
      ansible.posix.synchronize:
        src: "{{ src_path }}/"
        dest: "{{ extension_path }}/"
