- name: move devtools window
  hosts: localhost
  connection: local

  tasks:
    - name: check "xdotool" command
      shell:
        cmd: command -v xdotool
      changed_when: false

    - name: move devtools window
      script: >
        '{{ playbook_dir }}/mozdev/files/move_devtools_window.sh'
        {{ x_coord }}
        {{ y_coord }}
      vars:
        x_coord: 500
        y_coord: 250
      changed_when: false
