- name: package
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - mozdev

  vars:
    package_prefix:
    package_name: "{{ manifest.name }}"
    package_suffix: "{{ manifest.version }}"

  tasks:
    - name: clean up
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "{{ base_path }}/*.xpi"

    - name: package
      community.general.archive:
        path: "{{ src_path }}/"
        dest: "{{ base_path }}/{{ package_prefix }}{{ package_name }}{{ package_suffix }}.xpi"
        format: zip
        mode: "0644"
