- name: remove
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - mozdev

  tasks:
    - name: remove
      ansible.builtin.file:
        path: "{{ extension_path }}"
        state: absent
