- name: install
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - mozdev
  tasks:
    - name: run
      command:
        cmd: "{{ product_path }}/{{ product_executable }} -profile {{ profile_path }} {{ product_executable_args }}"

