- name: install
  hosts: localhost
  connection: local

  roles:
    - mozdev

  tasks:
    - name: run
      shell:
        cmd: >
          '{{ product_path }}/{{ product_executable }}'
          -profile '{{ profile_path }}'
          {{ product_executable_args }}"
      changed_when: false
