- name: sort messages
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - mozdev/vars/main.yml

  tasks:
    - name: check "jq" and "sponge" commands
      ansible.builtin.shell:
        cmd: >-
          command -v jq
          &&
          command -v sponge
      changed_when: false

    - name: sort messages
      ansible.builtin.command:
        cmd: >
          find "{{ src_path }}"
          -iname "messages.json"
          -exec bash -c "cat '{}' | jq -S | sponge '{}'" \;
      changed_when: false
