- name: sort messages
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - mozdev/vars/main.yml

  tasks:
    - name: check "jq" and "sponge" commands
      shell:
        cmd: command -v jq && command -v sponge
      changed_when: false

    - name: sort messages
      shell:
        cmd: >
          find "{{ src_path }}"
          -iname "messages.json"
          -exec bash -c "cat '{}' | jq -S | sponge '{}'" \;
      changed_when: false
