- name: sort messages
  hosts: localhost
  connection: local
  vars_files:
    - mozdev/vars/main.yml
  tasks:
    - name: check "jq" and "sponge" commands
      shell:
        cmd: command -v jq && command -v sponge
    - name: sort messages
      script: "mozdev/files/sort_messages.sh '{{ src_path }}'"
