- name: check archive
  stat:
    path: "{{ archive_path }}/{{ download_filename}}"
  register: product_archive
  
- name: download archive
  get_url:
    url: "{{ download_url }}"
    dest: "{{ archive_path }}/{{ download_filename}}"
  when: not product_archive.stat.exists  

- name: create product directory
  file:
    path: "{{ product_path }}"
    state: directory
  register: product_path_creation

- name: extract product archive
  command: 'tar -xvf "{{ archive_path }}/{{ download_filename}}" --strip 1 -C "{{ product_path }}"'
  when: product_path_creation.changed

- name: create profile directory
  file:
    path: "{{ profile_path }}"
    state: directory

- name: create addon directory
  file:
    path: "{{ extension_path }}"
    state: directory
