- name: create bin directory
  ansible.builtin.file:
    path: "{{ bin_path }}"
    state: directory
    mode: "0755"

- name: create archive directory
  ansible.builtin.file:
    path: "{{ archive_path }}"
    state: directory
    mode: "0755"

- name: download archive
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: "{{ archive_path }}/{{ download_filename }}"
    mode: "0644"

- name: create product directory
  ansible.builtin.file:
    path: "{{ product_path }}"
    state: directory
    mode: "0644"
  register: product_path_creation

- name: extract product archive # noqa no-handler
  ansible.builtin.unarchive:
    src: "{{ archive_path }}/{{ download_filename }}"
    dest: "{{ product_path }}"
    extra_opts:
      - "--strip 1"
  when: product_path_creation.changed

- name: create profile directory
  ansible.builtin.file:
    path: "{{ profile_path }}"
    state: directory
    mode: "0755"

- name: set prefs for profile
  ansible.builtin.lineinfile:
    path: "{{ profile_path }}/prefs.js"
    line: "{{ item }}"
    create: true
    mode: "0644"
  loop: "{{ profile_prefs }}"

- name: create addon directory
  ansible.builtin.file:
    path: "{{ extension_path }}"
    state: directory
    mode: "0755"
