- name: create bin direcotry
  file:
    path: "{{ bin_path }}"
    state: directory

- name: create archive direcotry
  file:
    path: "{{ archive_path }}"
    state: directory

- name: check archive
  stat:
    path: "{{ archive_path }}/{{ download_filename}}"
  register: product_archive
  
- name: download archive
  get_url:
    url: "{{ download_url }}"
    dest: "{{ archive_path }}/{{ download_filename}}"
  when: not product_archive.stat.exists  

- name: create product directory
  file:
    path: "{{ product_path }}"
    state: directory
  register: product_path_creation

- name: extract product archive
  unarchive:
    src: "{{ archive_path }}/{{ download_filename}}"
    dest: "{{ product_path }}"
    remote_src: yes
    extra_opts:
      - --strip 1
  when: product_path_creation.changed

- name: create profile directory
  file:
    path: "{{ profile_path }}"
    state: directory

- name: set prefs for profile
  lineinfile:
    path: "{{ profile_path }}/prefs.js"
    line: "{{ item }}"
    create: yes
  loop: "{{ profile_prefs }}"

- name: create addon directory
  file:
    path: "{{ extension_path }}"
    state: directory
